### ISSUE TITLE
Group react project Kanban setup

### ISSUE THREAD

**Issue by aceDavon** [aceDavon/space-traveler-hub#49]
## Code Review Issue for Group project kanban setup

[Link to the project](https://github.com/aceDavon/space-traveler-hub/projects)

> On this project, There are 2 collaborators: My Partner @Elijahdre and myself @aceDavon 

_We have already assigned ourselves different tasks as required by the curriculum and have also done some together_

**Comment by VICTOR-CHUKWU** [comment]
Hi Team, 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] projects assigned correctly

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
